all: zip upload

zip:
	mkdir -p build
	rm -f ./build/skill.zip
	cp -r ./venv/lib/python2.7/site-packages/dotenv build
	cp -r ./venv/lib/python2.7/site-packages/click build
	cp -r ./venv/lib/python2.7/site-packages/ordereddict.py build
	cp -r ./venv/lib/python2.7/site-packages/requests build
	cp -r ./venv/lib/python2.7/site-packages/fuzzywuzzy build
	cp -r ./venv/lib/python2.7/site-packages/Levenshtein build
	cp -r ../recipe_ranker/recipe_ranker build
	cp -r ./lambda_function.py ./my_cookbook build
	cp ~/.bigoven_key build/bigoven_key
	find build -name "*.swp" | xargs rm -f
	echo "PROD = True # AUTOGENERATED"  > ./build/my_cookbook/stage.py
	echo "BIGOVEN = True # AUTOGENERATED"  >> ./build/my_cookbook/stage.py
	cd build &&	zip -q -r skill.zip *

upload: zip
	aws lambda update-function-code --function-name MyCookbook --zip-file fileb://build/skill.zip
